language: cpp

sudo: required

compiler:
    - clang

script:
    - CC=clang CXX=clang++ CDEP_PATH=cdep python cdep/cdep.py
    - ls third-party/include
    - ls third-party/libs
    - cd src && make
    - src/all-test
